#!/usr/bin/env ruby
require 'getoptlong'
require 'smps'

def clidoc
  puts <<-CLIDOC

    #{$PROGRAM_NAME} [OPTION]

    -h, --help:
    show help

    -r, --role <rolename>
    IAM role to use. From ~/.aws/config

    -p, --param <param_name>
    Parameter name.

    -d, --debug [level]:
    Debug level.

  CLIDOC
end

opts = GetoptLong.new(
  ['--help', '-h', GetoptLong::NO_ARGUMENT],
  ['--role', '-r', GetoptLong::REQUIRED_ARGUMENT],
  ['--param', '-p', GetoptLong::REQUIRED_ARGUMENT],
  ['--debug', '-d', GetoptLong::OPTIONAL_ARGUMENT]
)

role = nil
param = nil
debug = 0

opts.each do |opt, arg|
  case opt
  when '--help'
    clidoc
    exit
  when '--role'
    role = arg
  when '--param'
    param = arg
  when '--debug'
    debug = if arg == ''
              1
            else
              arg.to_i
            end
  end
end

if role
  require 'awssession'
  require 'aws_config'
  
  profile_name = role
  profile = AWSConfig[profile_name]
  profile['name'] = profile_name

  awssession = AwsSession.new(profile: profile, debug: debug)
  awssession.start

  smps = SmPs.new(credentials: awssession.credentials)
else
  smps = SmPs.new
end

puts smps.parameter(param).to_s

# vim:set fileencoding=utf8 fileformat=unix filetype=ruby tabstop=2 expandtab:
